# Generated by Django 4.1.7 on 2023-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=100)),
                ('message', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('dateCreated',),
            },
        ),
    ]
